### PR TITLE
Fix cannot find .runfiles issue

### PR DESCRIPTION
**Pull request by chaonan99**
Fix cannot find .runfiles issue when install tensorboard with `pip install tensorboard --user`

### CODE REVIEW

**Comment by zihaolucky** [comment]
@chaonan99 Seems the patch cause an error. https://travis-ci.org/zihaolucky/tensorboard-distro/jobs/219250659#L2621

But I'm not sure about that. Did you change the patch file directly, or git diff xxx > xx.patch ?

**Comment by chaonan99** [comment]
I am new to patch so I just change it directly... What is the right way to do that though?

**Comment by chaonan99** [comment]
I think the change is definately wrong... I'll try to figure it out _(:з」∠)_

**Comment by zihaolucky** [comment]
As you might already notice, the patch file keep the line info. 

Check this https://github.com/zihaolucky/tensorboard-distro/blob/master/tools/pip_package/build_pip_package.sh#L115, try to build the binary before applying the patch. 

Then 
```bash
# add to git
git add tensorboard
# change the code
vim tensorboard
# make patch
git diff tensorboard > python-binary-and-runfiles.patch
```
and commit the patch.

**Comment by zihaolucky** [comment]
Please keep the python binary part in https://github.com/zihaolucky/tensorboard-distro/blob/master/tools/travis_wheel/python-binary-and-runfiles.patch when you make this fix.

**Comment by zihaolucky** [comment]
Never mind, just fix this issue first then try the Python3 later.

**Pull request merged**
